---
abstract: 'Kalman Filter(also known as Linear Quadratic Estimation) implementation for sensor fusion and such'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  blib: 1.01
  perl: 5.010
configure_requires:
  ExtUtils::MakeMaker: 0
  perl: 5.010
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-KalmanFilter
no_index:
  directory:
    - corpus
    - examples
    - inc
    - t
    - xt
  package:
    - DB
provides:
  Math::KalmanFilter:
    file: lib/Math/KalmanFilter.pm
    version: 0.05
requires:
  Moose: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/perl-math-kalmanfilter/issues
  homepage: https://metacpan.org/release/Math-KalmanFilter
  repository: git://github.com/shantanubhadoria/perl-math-kalmanfilter.git
version: 0.05
x_contributors:
  - 'Shantanu Bhadoria <shantanu.bhadoria@gmail.com>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
